apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Nvidia stuff
  - nvidia/nvidia-core.yml
  - nfd/nfd.yml
  - gfd/gpu-feature-discovery.yml

  # Monitoring stuff
  - monitoring/gpu_monitoring.yml
